name: Build

env:
  # deploymentNameBuild: ${{ github.event.inputs.deploymentNameBuild }}
  # location: ${{ github.event.inputs.location }}
  buildBicepPath: './deploy/build/main.bicep'
  buildJsonPath: './deploy/build/main.json' #(this file is produced after bicep file is compiled)
  buildParamsPath: './deploy/build/main.parameters.json'

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  #   inputs:
  #     deploymentNameBuild:
  #       description: 'Deployment Name Build'     
  #       required: true
  #     location:
  #       description: 'Location for deployment'     
  #       required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # LOGIN TO AZURE. THE LOGGED IN SESSION IS ACTIVE TILL A LOGOUT ACTION IS CALLED (OR THE JOB FINISHED)
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # SET CORRECT AZURE CONTEXT
      - name: 'Set context to subscription'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az account set -s '${{ secrets.AZURE_SUBSCRIPTION_ID }}'

      # BUILDING BICEP OUTPUTS A JSON ARM TEMPLATE
      - name: 'Build bicep 💪'
        run: |
          az bicep build --file ${{ env.buildBicepPath }}

      # DEPLOY THE SERVICES
      - name: 'Create / Update Azure resources'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment create -n ${{ secrets.DEPLOYMENT_NAME_BUILD }} -l ${{ secrets.LOCATION }} -f ${{ env.buildJsonPath }} -p ${{ env.buildParamPath }}
      
      # LOGOUT
      - name: logout
        run: |
          az logout