name: Build

env:
  # deploymentNameBuild: ${{ github.event.inputs.deploymentNameBuild }}
  # location: ${{ github.event.inputs.location }}
  buildBicepPath: './deploy/build/main.bicep'

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  #   inputs:
  #     deploymentNameBuild:
  #       description: 'Deployment Name Build'     
  #       required: true
  #     location:
  #       description: 'Location for deployment'     
  #       required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Import Az Module
      - name: Import Az Module
        shell: pwsd
        run: Import-Module Az

      # LOGIN TO AZURE. THE LOGGED IN SESSION IS ACTIVE TILL A LOGOUT ACTION IS CALLED (OR THE JOB FINISHED)
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # SET CORRECT AZURE CONTEXT
      - name: 'Set context to subscription'
        shell: pwsh
        run: Set-AzContext -Subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # DEPLOY THE SERVICES
      - name: 'Create / Update Azure resources'
        shell: pwsh
        run: New-AzSubscriptionDeployment -name ${{ secrets.DEPLOYMENT_NAME_BUILD }} -namePrefix ${{ secrets.PREFIX }} -location ${{ secrets.LOCATION }} -TemplateFile ${{ env.buildBicepPath }}
      
      # LOGOUT
      - name: logout
        run: |
          az logout